import { withIronSessionApiRoute } from "iron-session/next";
import sessionOptions from "../../../config/session"
import db from '../../../db'

export default withIronSessionApiRoute(
  function handler(req, res) {
    if (req.method !== 'POST')
      return res.status(404).end()
    switch(req.query.action) {
      case "login":
        return login(req, res)
      case "logout":
        return logout(req, res)
      case "signup":
        return signup(req, res)
      default:
        return res.status(404).end()
    }
  },
  sessionOptions
)

async function login(req, res) {
  const { username, password } = req.body
  try {
    const {
      password: _,
      ...otherFields
    } = await db.auth.login(username, password)
    req.session.user = otherFields
    await req.session.save()
    res.status(200).end()
  } catch(err) {
    res.status(400).json({error: err.message})
  }
}
async function logout(req, res) {
  await req.session.destroy()
  res.status(200).end()
}
async function signup(req, res) {
  try {
    const {username, password} = req.body
    const {
      password: _,
      ...otherFields
    } = await db.user.create(username, password)
    req.session.user = otherFields
    await req.session.save()
    res.redirect('/dashboard')
  } catch(err) {
    res.status(400).json({error: err.message})
  }
}
// import Head from 'next/head'
// import Image from 'next/image'
// import { useRouter } from 'next/router'
// import styles from '../../styles/Home.module.css'

// export async function getServerSideProps({params: {id}}) {
//   const response = await fetch(`http://www.omdbapi.com/?i=${id}&apikey=f7155445 `)
//   const data = await response.json()
//   console.log(data)
//   return {
//     props: {
//         movie: {
//             Title: data.Title,
//             Year: data.Year,
//             Rated: data.Rated
//         }

//     }
//   }
// }
// // f7155445

// export default function Home({movie: {Title, Year, Rated}}) {
//   const router = useRouter()
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>{Title}</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           {Title}
//         </h1>
//         <h2>{Year}</h2>
//         <p className={styles.description}>
//           {Rated}
//         </p>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
